fix error C2338: static_assert failed: magic_enum requires enum implementation and valid max and min. -- we're comparing an uint32_t type and an enum type in the static_assert here...